version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_TCP_PORT: 3306
    networks:
      - api
    expose:
      - 3306
    ports:
      - 3306:3306
    container_name: db
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - mysql
    networks:
      - api
    container_name: web-app


volumes:
  mysql-data:

networks:
  api:
    driver:
      bridge